### postgres username and password without SSL (Testing use only. Do not use this config file in any production setup)
### Solution from https://github.com/zalando/postgres-operator/issues/553#issuecomment-565304722
apiVersion: v1
kind: Secret
metadata:
  labels:
    application: spilo
    postgresql-operator: test-postgresql-db
  name: postgres.acid-minimal-cluster.credentials
  namespace: default
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
type: Opaque